---
# defaults file for cdap-ranger-auth
# defaults file for cdap-parameter-security
postgres_port: 5432
mysql_port: 3306
rangeradmin_username: "admin"
rangeradmin_password: "Sbe7UGkRBMF8"

cdap_loadbalancer_vip: "{{ site_floating_ip.ip }}"
cluster_name: '{{ site_inventory_name }}-reflex-platform'
site_deployment_type: "{{site_deployment_type}}"
install_using_public_repos: "false"
cdap_master_nodes: "master-nodes"
cdap_management_nodes: "management-nodes"
raf_docker_registry: "artifacts.ggn.in.guavus.com:4245"
ambari_admin_user: 'admin'
ambari_admin_password: 'Sbe7UGkRBMF8'
cdap_properties_dir: "/opt/guavus/ambari-api/cdap/properties"
site_default_rpm_repo_host: "artifacts.ggn.in.guavus.com:80"
cdap_version: '5.1.2'
cdap_major_version: '5.1.2'
hdp_version: '2.6.5.0'
spark2_2_home: "/usr/hdp/2.6.3.0-235/spark2"
install_guavus_accelerator: true


#---------------------------
#  cdap 
#----------------------------
cdap__security_authorization_enabled: 'true'
cdap__security_authorization_extension_jar_path: "/opt/cdap/master/ext/security/cdap-ranger-binding-0.1.4.jar"
cdap__security_authorization_extension_extra_classpath: "/usr/local/ranger-cdap-conf/"

#-----------------------
#  cdap ranger jar
#-----------------------
cdap__ranger_lookup_jar: cdap-ranger-lookup-0.1.4-jar-with-dependencies.jar

cdap__ranger_servicedef_cdap: |
  {
    "id": 11,
    "name": "cdap",
    "implClass": "co.cask.cdap.security.authorization.ranger.lookup.RangerLookupService",
    "label": "CDAP",
    "description": "CDAP",
    "resources": [
      {
        "itemId": 1,
        "name": "instance",
        "type": "string",
        "level": 10,
        "parent": "",
        "mandatory": true,
        "lookupSupported": false,
        "recursiveSupported": false,
        "excludesSupported": false,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "CDAP Instance",
        "description": "CDAP Instance"
      },
      {
        "itemId": 2,
        "name": "namespace",
        "type": "string",
        "level": 20,
        "parent": "instance",
        "mandatory": false,
        "lookupSupported": true,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Namespace",
        "description": "CDAP Namespace"
      },
      {
        "itemId": 30,
        "name": "application",
        "type": "string",
        "level": 30,
        "parent": "namespace",
        "mandatory": false,
        "lookupSupported": true,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Application",
        "description": "CDAP Application"
      },
      {
        "itemId": 40,
        "name": "artifact",
        "type": "string",
        "level": 30,
        "parent": "namespace",
        "mandatory": false,
        "lookupSupported": true,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Artifact",
        "description": "CDAP Artifact"
      },
      {
        "itemId": 50,
        "name": "dataset",
        "type": "string",
        "level": 30,
        "parent": "namespace",
        "mandatory": false,
        "lookupSupported": true,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Dataset",
        "description": "CDAP Dataset"
      },
      {
        "itemId": 60,
        "name": "dataset_module",
        "type": "string",
        "level": 30,
        "parent": "namespace",
        "mandatory": false,
        "lookupSupported": true,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Dataset Module",
        "description": "CDAP Dataset Module"
      },
      {
        "itemId": 70,
        "name": "dataset_type",
        "type": "string",
        "level": 30,
        "parent": "namespace",
        "mandatory": false,
        "lookupSupported": true,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Dataset Type",
        "description": "CDAP Dataset Type"
      },
      {
        "itemId": 80,
        "name": "secure_key",
        "type": "string",
        "level": 30,
        "parent": "namespace",
        "mandatory": false,
        "lookupSupported": true,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Secure Key",
        "description": "CDAP Secure Key"
      },
      {
        "itemId": 90,
        "name": "stream",
        "type": "string",
        "level": 30,
        "parent": "namespace",
        "mandatory": false,
        "lookupSupported": true,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Stream",
        "description": "CDAP Stream"
      },
      {
        "itemId": 100,
        "name": "principal",
        "type": "string",
        "level": 20,
        "parent": "instance",
        "mandatory": false,
        "lookupSupported": false,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Principal",
        "description": "Kerberos Principal"
      },
      {
        "itemId": 110,
        "name": "program",
        "type": "string",
        "level": 40,
        "parent": "application",
        "mandatory": false,
        "lookupSupported": true,
        "recursiveSupported": false,
        "excludesSupported": true,
        "matcher": "org.apache.ranger.plugin.resourcematcher.RangerDefaultResourceMatcher",
        "matcherOptions": {
          "wildCard": true,
          "ignoreCase": false
        },
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Program",
        "description": "CDAP Program"
      }
    ],
    "accessTypes": [
      {
        "itemId": 1,
        "name": "read",
        "label": "Read"
      },
      {
        "itemId": 2,
        "name": "write",
        "label": "Write"
      },
      {
        "itemId": 3,
        "name": "execute",
        "label": "Execute"
      },
      {
        "itemId": 4,
        "name": "admin",
        "label": "Admin"
      }
    ],
    "configs": [
      {
        "itemId": 1,
        "name": "cdap.username",
        "type": "string",
        "subType": "",
        "mandatory": true,
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Username"
      },
      {
        "itemId": 2,
        "name": "cdap.password",
        "type": "password",
        "subType": "",
        "mandatory": true,
        "validationRegEx": "",
        "validationMessage": "",
        "uiHint": "",
        "label": "Password"
      },
      {
        "itemId": 3,
        "name": "cdap.instance.url",
        "type": "string",
        "subType": "",
        "mandatory": true,
        "label": "Instance URL",
        "defaultValue": "",
        "validationRegEx": "",
        "validationMessage": ""
      }
    ],
    "enums": [],
    "contextEnrichers": [],
    "policyConditions": []
  }
