---

cdap_loadbalancer_vip: "{{ site_floating_ip.ip }}"
cluster_name: '{{ site_inventory_name }}-reflex-platform'
site_deployment_type: "{{{site_deployment_type}}"
install_using_public_repos: "false"
cdap_master_nodes: "master-nodes"
cdap_management_nodes: "management-nodes"
raf_docker_registry: "artifacts.ggn.in.guavus.com:4245"
ambari_admin_user: 'admin'
ambari_admin_password: 'Sbe7UGkRBMF8'
cdap_properties_dir: "/opt/guavus/ambari-api/cdap/properties"
site_default_rpm_repo_host: "artifacts.ggn.in.guavus.com:80"
cdap_version: '5.1.0'
cdap_major_version: '5.1.0'
hdp_version: '2.6.5.0'
