#--------------------------
# Perimeter security enable
#--------------------------

is_security_enabled: true                   # Set true to enable cdap security

#---------------------------
# Kerberos enabled on cluser
#---------------------------

is_kerberos_auth_enabled: true              # Set true to enable kerberos authorization

#---------------------
# Enable Authorization 
#---------------------

is_security_authorization_enabled: true     # Set true to enable authorization


#----------------------
# Enable Authentication
#----------------------
is_dashboard_ssl_disable_cert_check: true                                   # True to disable SSL certificate check from CDAP UI 
is_security_authentication_handler_debug: true                              
is_security_authentication_handler_useLdaps: true                           # True to enable use of LDAPS
is_security_authentication_handler_ldapsVerifyCertificate: false            # True to enable verification of ssl certificate used by LDAP

security_authentication_handler_hostname: "guavus.com"
security_authentication_handler_port: "636"
security_authentication_handler_userBaseDn: "OU=gurgaon,OU=India,OU=UserIDs,DC=guavus,DC=com"
security_authentication_handler_userRdnAttribute: "sAMAccountName"
security_authentication_handler_userObjectClass: "user"
security_authentication_handler_userIdAttribute: "sAMAccountName"
security_authentication_handler_roleBaseDn: "OU=Groups,DC=guavus,DC=com"
security_authentication_handler_roleNameAttribute: "cn"
security_authentication_handler_roleMemberAttribute: "member"
security_authentication_handler_roleObjectClass: "group"                                                      
security_authentication_handler_bindDn: "CN=svc-devops,OU=ApplicationObjects,OU=Custom,DC=guavus,DC=com"      # The distinguish Name to bind AD server
security_authentication_handler_bindPassword: changeit                                            # Password used to bind to AD server

#-------------------------------------------------------------
# SSL cert , SSL key , Truststore and Keystore configuration
# Enable below flags to use in-built provided truststore,
# keystore, ssl cert and key.
# THIS IS NOT RECOMMENDED FOR PRODUCTION.
#-------------------------------------------------------------
use_default_ssl_cert: true                 # Set true to use default ssl cert 
use_default_store: true                    # Set true to use default keystore

#----------------------------------------------------------
#            Configs for keystore and truststore
# Below Configs will exists on CDAP management node. Do not 
# change below config if use_default_store values is true 
# as it will auto generated by provisioner at given paths. 
#----------------------------------------------------------
security_auth_server_ssl_truststore_path: /etc/cdap/truststore.jks          # TrustStore file location 
security_auth_server_ssl_keystore_path: /etc/cdap/keystore.jks              # KeyStore file location
router_ssl_keystore_path: /etc/cdap/keystore.jks                            # KeyStore file location
security_auth_server_ssl_truststore_password: changeit                      # Truststore password
security_auth_server_ssl_keystore_password: changeit                        # KeyStore password
security_auth_server_ssl_keystore_keypassword: changeit                     # KeyStore Key password


#----------------------------------------------------------
#          Configs for SSL cert and key
# Below Configs will exists on CDAP management
# node. Do not change below config if use_default_ssl_cert
# is true as it will auto generated by provisioner at given 
# paths. 
#----------------------------------------------------------
dashboard_ssl_cert: /etc/cdap/cdap-ui-cert.pem                              # SSL cert file location
dashboard_ssl_key: /etc/cdap/cdap-ui-key.key                                # SSL key file location
router_ssl_keystore_password: changeit                               # KeyStore password
router_ssl_keystore_keypassword: changeit                            # KeyStore key password
