---
 
- name: Retrieve facts all host
  hosts:
    - all
  gather_facts: true
  any_errors_fatal: True
  tags:
    - 'always'
  tasks: []
 
- name: UnInstall CDAP from Ambari
  hosts:
    - all:!loadbalancer-nodes
  any_errors_fatal: true
  vars_files:
    - ../../inventory/group_vars/all.yml
  roles:
    - cdap/undeploy
