---
 
- name: Retrieve facts all host
  hosts:
    - all
  gather_facts: true
  any_errors_fatal: True
  tags:
    - 'always'
  tasks: []
 
- name: UnInstall CDAP from Ambari
  hosts:
    - all:!loadbalancer-nodes
  any_errors_fatal: true
  vars:
    - install_using_public_repos: "false"
    - cdap_master_nodes: "master-nodes"
    - cdap_management_nodes: "management-nodes"
    - cdap_loadbalancer_vip: "192.168.134.125"
    - site_default_rpm_repo_host: 'artifacts.ggn.in.guavus.com:80'
    - cluster_name: 'arch001-reflex-platform'
    - ambari_admin_user: 'admin'
    - ambari_admin_password: 'Sbe7UGkRBMF8'
    - cdap_properties_dir: "/opt/guavus/ambari-api/cdap/properties"
    - site_default_rpm_repo_host: "artifacts.ggn.in.guavus.com:80"
    - cdap_version: '4.3.4'
    - cdap_major_version: '4.3'
    - hdp_version: '2.6.5.0'
  roles:
    - cdap/undeploy
