---

- name: Retrieve facts all host
  hosts:
    - all
  gather_facts: true
  any_errors_fatal: True
  tags:
    - 'always'
  tasks: []
 
- name: Deploy CDAP to Ambari
  hosts:
    - all:!loadbalancer-nodes
  any_errors_fatal: true
  vars_files:
    - ../../inventory/templates/group_vars/global/all/raf/cdap.yml
  roles:
    - raf/cdap/deploy

