---
# defaults file for cdap-ui

--------------------
CDAP UI THEME CONFIG
--------------------

cdap__ui_theme_name: 'afe'


cdap__ui_theme_file: 'ui/server/config/themes/{{cdap__ui_theme_name}}.json'

cdap__data_tx_max_timeout: 3600

cdap__data_tx_timeout: 3600

