---

- name: Retrieve facts all host
  hosts:
    - all
  gather_facts: true
  any_errors_fatal: True
  tags:
    - 'always'
  tasks: []

- name: "Set raf docker registry"
  hosts:
    - management-nodes
  tags:
    - always
  tasks:
    - set_fact:
        raf_docker_registry: '{{ docker_default_registry }}'
      when: site_connectivity == 'offline'
    - debug:
        msg: "Raf docker registry is: {{ raf_docker_registry }}"
    - set_fact:
        site_floating_ip:
          ip: "{{ hostvars[groups['management-nodes'][0]]['ansible_default_ipv4']['address'] }}"
      when: site_deployment_type == 'NONHA'
    - debug:
        msg: "Setup type is NONHA and site_floating_ip.ip is: {{ site_floating_ip.ip }}"
      when: site_deployment_type == 'NONHA'
 
- name: Deploy CDAP to Ambari
  hosts:
    - all:!loadbalancer-nodes
  any_errors_fatal: true
  roles:
    - raf/cdap/deploy

